### ISSUE TITLE
Security risk.

### ISSUE THREAD

**Issue by alimd** [mahnunchik/telegram-promise#1]
Please don't keep your own bot key in source!
Anyone can control your bot.
I suggest you to remove the bot and recreate it to change the token and remove it from source.

**Comment by mahnunchik** [comment]
Hi @AliMD

If you mean the key `123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11` it is from official documentation https://core.telegram.org/bots/api#making-requests.

Thanks for the advice!

**Comment by alimd** [comment]
ooops ;)
